version: "3.9"

services:
  last_bot:
    build: .
    container_name: last_bot
    restart: unless-stopped

    # Load secrets from .env file
    env_file:
      - .env

    # Mount local folders if needed (optional)
    volumes:
      - ./downloads:/app/downloads
      - ./encodes:/app/encodes
      - ./thumbnails:/app/thumbnails

    # Uncomment if your bot uses a webhook or HTTP server
    # ports:
    #   - "8080:8080"

    # Optional: logging limits
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
